---
- name: check controller status with jobid to get status
  uri:
    url: "{{ nsx_jobstatus }}{{ jobid }}"
    method: GET
    user: "{{ nsx_user }}"
    password: "{{ nsx_password }}"
    force_basic_auth: yes
    HEADER_Content-Type: "{{ nsx_header }}"
    return_content: yes
    validate_certs: no
    creates: "{{ controller_jobstatus }}"
  register: controller_create

