---
- name: Get Cluster IDs for NSX Manager Configuration
  ignore_errors: yes
  local_action:
    module: vcenter_query
    host: "{{ vcenter_host }}"
    login: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    port: "{{ vcenter_port }}"
    resourcename: "{{ item.vcenter_object_name }}"
    resourcevarname: "{{ item.vcenter_object_var }}"
    resourcetype: 'cluster'
    getfacts: 'yes'
  with_items:
    - { vcenter_object_name: "{{ vio_cluster_mgmt }}", vcenter_object_var: 'vio_cluster_mgmt_id' }
    - { vcenter_object_name: "{{ vio_cluster_edge }}", vcenter_object_var: 'vio_cluster_edge_id' }
    - { vcenter_object_name: "{{ vio_cluster_compute }}", vcenter_object_var: 'vio_cluster_compute_id' }

- name: Get Datastore IDs for NSX Manager Configuration
  ignore_errors: yes
  local_action:
    module: vcenter_query
    host: "{{ vcenter_host }}"
    login: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    port: "{{ vcenter_port }}"
    resourcename: "{{ item.vcenter_object_name }}"
    resourcevarname: "{{ item.vcenter_object_var }}"
    resourcetype: 'datastore'
    getfacts: 'yes'
  with_items:
    - { vcenter_object_name: "{{ controller_ds_name }}", vcenter_object_var: 'vio_ds_id' }

- name: Get vDS ID for NSX Manager Configuration
  ignore_errors: yes
  local_action:
    module: vcenter_query
    host: "{{ vcenter_host }}"
    login: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    port: "{{ vcenter_port }}"
    resourcename: "{{ item.vcenter_object_name }}"
    resourcevarname: "{{ item.vcenter_object_var }}"
    resourcetype: 'dvs'
    getfacts: 'yes'
  with_items:
    - { vcenter_object_name: "{{ vds_name_test }}", vcenter_object_var: 'vio_vds_id' }

- name: Get Management PortGroup ID ID for NSX Manager Configuration
  ignore_errors: yes
  local_action:
    module: vcenter_query
    host: "{{ vcenter_host }}"
    login: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    port: "{{ vcenter_port }}"
    resourcename: "{{ item.vcenter_object_name }}"
    resourcevarname: "{{ item.vcenter_object_var }}"
    resourcetype: 'dvs-port'
    getfacts: 'yes'
  with_items:
    - { vcenter_object_name: "{{ mgmt_grp_test }}", vcenter_object_var: 'vio_mgmtpg_id' }

- name: Get Cluster Resource Group Object ID
  ignore_errors: no
  local_action:
    module: get_cluster_resgroup
    host: "{{ vcenter_host }}"
    login: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    port: "{{ vcenter_port }}"
    cluster: "{{ item.vcenter_name }}"
    resourcevarname: "{{ item.vcenter_var }}"
  with_items:
    - { vcenter_name: "{{ vio_cluster_mgmt }}", vcenter_var: 'vio_mgmt_resgroup_id' }
    - { vcenter_name: "{{ vio_cluster_edge }}", vcenter_var: 'vio_edge_resgroup_id' }
    - { vcenter_name: "{{ vio_cluster_compute }}", vcenter_var: 'vio_compute_resgroup_id' }

- name: debug and test vars
  debug: var={{ item }}
  with_items:
    - vio_cluster_mgmt_id
    - vio_cluster_edge_id
    - vio_cluster_compute_id
    - vio_ds_id
    - vio_vds_id
    - vio_mgmtpg_id
    - vio_mgmt_resgroup_id
    - vio_edge_resgroup_id
    - vio_compute_resgroup_id
