---
- name: Sync Host Preparation
  command: cp "{{ instv_xml }}" "{{ item }}"
  with_items:
    - "{{ nsx_tmp }}/{{ vio_cluster_edge_id }}.xml"
    - "{{ nsx_tmp }}/{{ vio_cluster_compute_id }}.xml"

- name: Adding Cluster Object IDs
  xml:
    file: "{{ item.file_name }}"
    xpath: /nwFabricFeatureConfig/resourceConfig/resourceId
    value: "{{ item.cluster_id }}"
  with_items:
    - { file_name: "{{ nsx_tmp }}/{{ vio_cluster_edge_id }}.xml", cluster_id: "{{ vio_cluster_edge_id }}" }
    - { file_name: "{{ nsx_tmp }}/{{ vio_cluster_compute_id }}.xml", cluster_id: "{{ vio_cluster_compute_id }}" }

- name: Sync Network Virtualization Components for Clusters
  uri:
    url: "{{ nsx_sync }}"
    method: POST
    user: "{{ nsx_user }}"
    password: "{{ nsx_password }}"
    body: "{{ lookup('file', nsx_tmp + '/' + item) }}"
    force_basic_auth: yes
    HEADER_Content-Type: "{{ nsx_header }}"
    validate_certs: no
    return_content: yes
  with_items:
    - "{{ vio_cluster_edge_id }}.xml"
    - "{{ vio_cluster_compute_id }}.xml"
  register: instvirt_syncup

- name: Remove files
  file: path="{{ item }}" state=absent
  with_items:
    - "{{ nsx_tmp }}/{{ vio_cluster_edge_id }}.xml"
    - "{{ nsx_tmp }}/{{ vio_cluster_compute_id }}.xml"

