---
- name: install virt setup xml a
  command: cp "{{ instv_xml }}" "{{ instv_tmpa }}"
  when: sys_status == "{{ success_status }}"

- name: add values to inst_virt a
  xml:
    file: "{{ instv_tmpa }}"
    xpath: /nwFabricFeatureConfig/resourceConfig
    value: "{{ mgmt_id }}"

- name: inst_virt put request a
  uri:
    url: "{{ nsx_inst_virt }}"
    method: POST
    user: "{{ nsx_user }}"
    password: "{{ nsx_password }}"
    body: "{{ lookup('file','/tmp/files/inst_virta.xml') }}"
    force_basic_auth: yes
    HEADER_Content-Type: "{{ nsx_header }}"
  register: inst_virtoutputa

- name: inst_virt Set new fact
  set_fact:
    inst_a_virt_status: "{{ inst_virtoutputa.status }}"

- name: install virt setup xml b
  command: cp "{{ instv_xml }}" "{{ instv_tmpb }}"
  when: inst_a_virt_status == "{{ success_status }}"

- name: add values to inst_virt b
  xml:
    file: "{{ instv_tmpb }}"
    xpath: /nwFabricFeatureConfig/resourceConfig
    value: "{{ edge_id }}"

- name: inst_virt put request b
  uri:
    url: "{{ nsx_inst_virt }}"
    method: POST
    user: "{{ nsx_user }}"
    password: "{{ nsx_password }}"
    body: "{{ lookup('file','/tmp/files/inst_virtb.xml') }}"
    force_basic_auth: yes
    HEADER_Content-Type: "{{ nsx_header }}"
  register: inst_virtoutputb

- name: inst_virt Set new fact
  set_fact:
    inst_b_virt_status: "{{ inst_virtoutputb.status }}"

- name: install virt setup xml c
  command: cp "{{ instv_xml }}" "{{ instv_tmpc }}"
  when: inst_b_virt_status == "{{ success_status }}"

- name: add values to inst_virt c
  xml:
    file: "{{ instv_tmpc }}"
    xpath: /nwFabricFeatureConfig/resourceConfig
    value: "{{ compt_id }}"

- name: inst_virt put request c
  uri:
    url: "{{ nsx_inst_virt }}"
    method: POST
    user: "{{ nsx_user }}"
    password: "{{ nsx_password }}"
    body: "{{ lookup('file','/tmp/files/inst_virtc.xml') }}"
    force_basic_auth: yes
    HEADER_Content-Type: "{{ nsx_header }}"
  register: inst_virtoutputc

- name: inst_virt Set new fact
  set_fact:
    inst_c_virt_status: "{{ inst_virtoutputc.status }}"

- name: remove file
  file: path="{{ item }}" state=absent
  with_items:
     - "{{ instv_tmpa }}"
     - "{{ instv_tmpb }}"
     - "{{ instv_tmpc }}"

