# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
---
- name: Create the nsx defaults/main.yml file
  template: src=../templates/defaults.yml.j2 dest=/opt/chaperone-ansible/roles/nsx/defaults/main.yml
  tags:
    - create_vars_files

- name: Deploy NSX Manager
  include: deploy-nsx-ova.yml

- name: Configure NSX Manager
  include: base-config-nsx.yml

