---
- name: netscop
  command: cp /etc/ansible/roles/nsx/files/netscop.xml /tmp/netscop.xml

- name: 1st parent
  xml:
    file: /tmp/netscop.xml
    xpath: /<vdnScope>
    add_children:
           - name: 
           - clusters:
           - controlPlaneMode:

- name: add 1 parent values
  xml: file=/tmp/netscop.xml xpath=/vdnScope/name value='NAME'

- name: add 1 parent values
  xml: file=/tmp/netscop.xml xpath=/vdnScope/controlPlaneMode value='UNICAST_MODE'

- name: add 2nd child
  xml: 
    file: /tmp/netscop.xml
    xpath: /vdnScope/clusters
    add_children:
           - cluster:

- name: add 3rd child
  xml:
    file: /tmp/netscop.xml
    xpath: /vdnScope/clusters/cluster
    add_children:
           - cluster:

- name: add 4th child
  xml: 
    file: /tmp/netscop.xml
    xpath: /vdnScope/clusters/cluster/cluster
    add_children:
           - objectId: 'domain-11111'

- name: add 3rd child
  xml:
    file: /tmp/netscop.xml
    xpath: /vdnScope/clusters/cluster
    add_children:
           - cluster:

- name: add 4th child
  xml: 
    file: /tmp/netscop.xml
    xpath: /vdnScope/clusters/cluster/cluster
    add_children:
           - objectId: 'domain-222222'














