---
- name: Deploy NSX OVA
  shell: >
    {{ ovftool }}
    '--name={{ nsx_name }}'
    --acceptAllEulas
    --allowExtraConfig
    --noSSLVerify
    --diskMode=thin
    '--datastore={{ nsx_datastore }}'
    '--network={{ mgmt_grp }}'
    '--prop:vsm_cli_en_passwd_0={{ cli_pass }}'
    '--prop:vsm_cli_passwd_0={{ cli_pass }}'
    --ipProtocol=IPv4
    '--prop:vsm_cli_en_passwd_0={{ cli_pass }}'
    '--prop:vsm_cli_passwd_0={{ cli_pass }}'
    '--prop:vsm_hostname={{ nsx_hostname }}'
    '--prop:vsm_ip_0={{ nsx_ip }}'
    '--prop:vsm_netmask_0={{ nsx_netmask }}'
    '--prop:vsm_gateway_0={{ nsx_gateway }}'
    '--prop:vsm_dns1_0={{ nsx_dns }}'
    '--prop:vsm_domain_0={{ nsx_domain }}'
    '--prop:vsm_ntp_0={{ ntp_svr }}'
    '--prop:vsm_isSSHEnabled={{ nsx_ssh_enabled }}'
    '{{ nsx_ova_location }}/{{ nsx_ova }}'
    'vi://{{ vcenter_user | urlencode }}:{{ vcenter_password | urlencode }}@{{ vcenter_host }}/{{ datacenter_name }}/host/{{ vio_cluster_mgmt }}/'
  register: nsx_ova_deploy

- name: debug deploy
  debug: var=nsx_ova_deploy

- name: Start NSX Manager 
  vsphere_guest:
    vcenter_hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    guest: "{{ nsx_name }}"
    state: powered_on
  when: nsx_poweron == "ON"
