---
- name: segment id
  command: cp "{{ seg_xml }}" "{{ seg_tmp }}"

- name: xml for segid
  xml:
    file: "{{ seg_tmp }}"
    xpath: /segmentRange
    add_children:
           - id: "{{ segment_id }}"
           - name: "{{ segment_name }}"
           - desc: "{{ segment_desc }}"
           - begin: "{{ segment_begin }}"
           - end: "{{ segment_end }}"

- name: segment id post
  uri:
    url: "{{ nsx_seg }}"
    method: POST
    user: "{{ nsx_user }}"
    password: "{{ nsx_password }}"
    body: "{{ lookup('file', item) }}"
    force_basic_auth: yes
    HEADER_Content-Type: "{{ nsx_header }}"
    validate_certs: no
    status_code: 201
  with_items:
    - "{{ seg_tmp }}"
  register: segment_create

- name: Fail when status not 201
  fail:
    msg: "Failed to create segment {{ segment_name }}"
  when: item.status != 201
  with_items: "{{ segment_create.results }}"

- name: remove file
  file: path="{{ seg_tmp }}" state=absent
