---
- name: scope xml
  command: cp "{{ vdnscope_xml }}" "{{ vdnscope_tmp }}"

- name: scope parent elements xml
  xml:
    file: "{{ vdnscope_tmp }}"
    xpath: /vdnScope
    add_children:
           - name: "{{ vdnscope_name }}"
           - clusters:

- name: scope 1st child elements xml
  xml:
    file: "{{ vdnscope_tmp }}"
    xpath: /vdnScope/clusters
    add_children:
           - cluster:

- name: scope 2st child elements xml
  xml:
    file: "{{ vdnscope_tmp }}"
    xpath: /vdnScope/clusters/cluster
    add_children:
           - cluster:

- name: scope 3st child elements xml
  xml:
    file: "{{ vdnscope_tmp }}"
    xpath: /vdnScope/clusters/cluster/cluster
    add_children:
           - objectId: "{{ vio_cluster_edge_id }}"

- name: scope 1st child elements xml
  xml:
    file: "{{ vdnscope_tmp }}"
    xpath: /vdnScope/clusters
    add_children:
           - cluster:

- name: scope 2st child elements xml
  xml:
    file: "{{ vdnscope_tmp }}"
    xpath: /vdnScope/clusters/cluster
    add_children:
           - cluster:

- name: scope 2st child elements xml
  xml:
    file: "{{ vdnscope_tmp }}"
    xpath: /vdnScope/clusters/cluster/cluster
    add_children:
           - objectId: "{{ vio_cluster_compute_id }}"

- name: scope parent elements xml
  xml:
    file: "{{ vdnscope_tmp }}"
    xpath: /vdnScope
    add_children:
           - controlPlaneMode: "{{ vdnscope_mode }}"

- name: vdnscopes POST for Compt/Edge Cluster
  uri:
    url: "{{ nsx_scope }}"
    method: POST
    user: "{{ nsx_user }}"
    password: "{{ nsx_password }}"
    body: "{{ lookup('file', item) }}"
    force_basic_auth: yes
    HEADER_Content-Type: "{{ nsx_header }}"
    validate_certs: no
    status_code: 201
  with_items:
    - "{{ vdnscope_tmp }}"
  register: vdnscope_create

- name: Fail when status not 201
  fail:
    msg: "Failed to create Transport zone {{ vdnscope_name }}"
  when: item.status != 201
  with_items: "{{ vdnscope_create.results }}"

- name: remove file
  file: path="{{ vdnscope_tmp }}" state=absent
